### PR TITLE
Update manifest.toml

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by csolisr** [comment]
Regarding the issue with the database, you might want to look at this: https://github.com/LemmyNet/lemmy/issues/3756

Seems like we're currently using an unsupported version of PostgreSQL. Their Docker image is using PostgreSQL version 15, and IIRC Debian only supports version 13.

**Comment by ericgaspar** [comment]
!bookwormtestme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!bookwormtestme

**Comment by ericgaspar** [comment]
!bookwormtestme

**Comment by alexAubin** [comment]
Current issue seems to be related to : `thread 'main' panicked at 'Couldn't run DB Migrations: Failed to run 2023-07-08-101154_fix_soft_delete_aggregates with: syntax error at or near "trigger"', crates/db_schema/src/utils.rs:221:25`

**Comment by CtheCondor** [comment]
How might I try to load/install this branch to see if it runs on my local instance? Or is the last failure indicative that it won't across the board and its not so much hit-or-miss by instance?

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
