### PR TITLE
The link redirected to a 404 page

### PR DESCRIPTION
**Pull request by MyNameIsTroll**
## Problem

Change this link https://join.lemmy.ml/join/  (ERROR 404)

## Solution

change to this : https://join.lemmy.ml

## PR Status

- [ OK ] Code finished and ready to be reviewed/tested
- [ OK ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
Thanks for the correction.
The link to change is on the manifest -> https://github.com/YunoHost-Apps/lemmy_ynh/blob/1681bfab08bdc5e943d5fdaf5b5069066f84d35d/manifest.json#L13
The readme is autogenerated with the manifest links.

**Comment by MyNameIsTroll** [comment]
I don't know if the link to "demo" makes sense because it redirects to the instance search page. And this link already exists in the "Documentation and resources" part
Maybe we should put the link to the main instance as demo? https://lemmy.ml/

**Comment by tituspijean** [comment]
Superseded by #10 

(And btw the brackets are meant to look like that when ticked: [X]

- [X] test
)

**Comment by ericgaspar** [comment]
[X] retest

**Comment by ericgaspar** [comment]
crap...

**Pull request closed without merging**
